version: '3.8'

services:
  style-starter-kit:
    build: .
    container_name: style_starter_kit_container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/style-starter-kit
    working_dir: /usr/src/style-starter-kit
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run start-windows"

