name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Check for 'Release' in commit message
        id: check_release
        run: |
          if git log -1 --pretty=%B | grep -q 'Release'; then
            echo "Release found in commit message"
            echo "::set-output name=release::true"
          else
            echo "Release not found in commit message"
            echo "::set-output name=release::false"
          fi

      - name: Check if version is higher than npm
        id: check_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NPM_VERSION=$(npm view $(node -p "require('./package.json').name") version)
          if [ "$CURRENT_VERSION" != "$NPM_VERSION" ]; then
            echo "Current version is higher than npm version"
            echo "::set-output name=version_higher::true"
          else
            echo "Current version is not higher than npm version"
            echo "::set-output name=version_higher::false"
          fi

      - name: Publish
        if: steps.check_release.outputs.release == 'true' && steps.check_version.outputs.version_higher == 'true'
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
